variables:
  PROJECT: "app"
  CI_REGISTRY: "registry.ftech.ai"
  CI_REGISTRY_IMAGE: "registry.ftech.ai/funzy/moiban"


stages:
  - build
  - deploy


.build_template: &build
  image: docker:19.03.12
  before_script:
    - mv .env-$ENV_NAME .env
    - cat .env
    - docker info
    - docker images
    - echo $REGISTRY_PUSH_USER
    - echo $REGISTRY_PUSH_PASSWORD
    - echo $CI_REGISTRY
    - docker login -u "$REGISTRY_PUSH_USER" -p "$REGISTRY_PUSH_PASSWORD" "$CI_REGISTRY"
  script:
    - export APP_VERSION=$ENV_NAME-$(date +'%Y-%m-%d_%H-%M-%S')-`[ -n "$CI_COMMIT_TAG" ] && echo $CI_COMMIT_TAG || echo $CI_COMMIT_SHORT_SHA` && echo $APP_VERSION
    - docker build -t "$CI_REGISTRY_IMAGE:$APP_VERSION" -t "$CI_REGISTRY_IMAGE"  . -f Dockerfile
    - docker push "$CI_REGISTRY_IMAGE:$APP_VERSION"
  services:
    - name: docker:19.03.12-dind
      alias: docker
  allow_failure: false
  # when: manual
  tags: [build]


build-dev:
  stage: build
  variables:
    ENV_NAME: dev
  only:
    - cicd
    - dev
  <<: *build
  when: manual


build-prod:
  stage: build
  variables:
    ENV_NAME: prod
  only:
    - cicd
    - prod
    - tags
  <<: *build
  when: manual
