version: "3.7"

networks:
  moiban-frontend-network:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: strapi-moiban-web
    container_name: moiban-web
    restart: unless-stopped
    ports:
      - "3003:3000"
    networks:
      - moiban-frontend-network
